language: java
jdk: oraclejdk7

before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1
  - export COMPONENTS=build-tools-19.0.0,android-19,sysimg-19,extra-android-support
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/master/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
  - source ~/.android-sdk-installer/env

install:
  - TERM=dumb ./gradlew assembleDebug

script:
  - TERM=dumb ./gradlew testDebug
